rtl/core/approxflex_pkg.sv
rtl/core/operand_rounder_mag8to5.sv
rtl/core/ora_signed_mult8.sv
rtl/rmmec/rmm2ec.sv
rtl/core/rmmec4_transprecision_fabric.sv
rtl/core/approxflex_product_router.sv
rtl/core/fxp24_acc_sat.sv
rtl/core/fxp24_requant.sv
rtl/core/shared_sigmoid_pwl8.sv
rtl/core/reconfig_af_sharedsig.sv
rtl/core/approx_flex_pe.sv
rtl/core/approx_flex_pe_forward.sv
rtl/core/true_systolic_array.sv
rtl/core/tile_self_control.sv
rtl/core/configurable_systolic_array.sv
rtl/memory/dual_port_sram.sv
rtl/memory/banked_multi_address_mem.sv
rtl/memory/pingpong_buffer.sv
rtl/memory/local_memory_subsystem.sv
rtl/control/axi_lite_ctrl.sv
rtl/control/tile_scheduler.sv
rtl/control/k_tail_mask.sv
rtl/control/packed_operand_mask.sv
rtl/control/conv_address_gen.sv
rtl/control/implicit_gemm_streamer.sv
rtl/control/precision_address_adapter.sv
rtl/control/int2_pack4.sv
rtl/control/fp4_pack2.sv
rtl/control/descriptor_fifo.sv
rtl/control/vector_unpacker.sv
rtl/control/output_packer.sv
rtl/control/layer_exec_engine.sv
rtl/system/memory_compute_bridge.sv
rtl/system/compute_tile_datapath.sv
rtl/dma/axi4_read_dma.sv
rtl/dma/axi4_write_dma.sv
rtl/dma/axi_dma_engine.sv
rtl/postproc/residual_add.sv
rtl/postproc/nearest_upsample2x.sv
rtl/postproc/postproc_dispatch.sv
rtl/postproc/nms_topk.sv
rtl/top/approxflex_yolo_top.sv
